#!/usr/bin/env python2

##
## Program name: chatserve
## Author: Andrew Swaim
## Date: October 2019
## Description: A chat host that waits on a port specified on the command line for 
##     connections from other chat hosts. Once a connection is established, can chat 
##     back and forth with the other host until one of them sends a "\quit" command,
##     in which case the connection is closed but chatserve will remain
##     active waiting for more connections.
##

import signal
import sys
import re
from socket import *

MSGLEN = 500 # max message length for sending or receiving

# Name: run()
# Desc: The main function that starts the server.
# Pre : chatserve application is run, specifying a port on the command line.
# Post: chatserve server is running and listening for connections.
def run():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: chatserve [port]")

    print("Welcome to chatserve, your friendly chatting server!")
    print("(Press CTRL + C at any time to exit)")

    signal.signal(signal.SIGINT, bye) # bind SIGINT signal to handler function
    sock = setup()                    # setup the socket connection
    user = getUser()                  # prompt for a get the user's name
    
    # run indefinitely until a SIGINT is received
    print("Welcome " + user + "!")
    while True:
        print("You are in the waiting room. Waiting for someone to join...")
        
        # a new connection is established
        conn, addr = sock.accept()

        # handshake with client to receive client's name 
        client = conn.recv(10) # max 10 chars for username
        conn.send(user)
        print(client + " has joined the chatroom!")

        chat(conn, user, client) # begin chat loop
        conn.close()             # if the chat loop ends, close the connection


# Name: setup()
# Desc: Sets up a TCP socket on the port num specified on the command line and begins listening.
# Rtrn: The file descriptor for the opened and listening connection
# Pre : A port number was specified on the command line when the application was started.
# Post: a TCP socket is created on the specified port and begins listening.
def setup():

    # python socket programming info from official docs
    # in section about python socket programming examples
    # https://docs.python.org/2/library/socket.html#example
    port = sys.argv[1]
    for res in getaddrinfo(gethostname(), port, AF_UNSPEC, SOCK_STREAM, 0, AI_PASSIVE):
        af, socktype, proto, canonname, sa = res
        try:
            sock = socket(AF_INET, SOCK_STREAM)
        except error as msg:
            sock = None
            continue
        try:
            sock.bind((gethostname(), int(port)))
            sock.listen(1)
        except error as msg:
            sock.close()
            sock = None
            continue
        break
    if sock is None:
        print("ERROR: could not open socket at port " + port)
        sys.exit(1)
    return sock


# Name: getUser()
# Desc: Prompts for and gets username, using regex matching for validation of format.
# Pre : None.
# Post: A correctly formatted and validated username is returned.
def getUser():

    # python regex info from official docs
    # https://docs.python.org/2/library/re.html#module-contents
    user = raw_input("Please enter a one word username, up to 10 characters: ")
    regex = re.compile("^[A-Za-z]{1,10}$")
    while not regex.match(user):
        print("Invalid username format")
        user = raw_input("Please enter a one word username, up to 10 characters: ")
    return user


# Name: chat()
# Desc: The main chat loop where the user and client take turns sending messages
#           back and forth with each other until the connection is terminated.
# Arg1: conn - the connection that is established with the client when the socket accepted
#           the connection.
# Arg2: user - the username of the server user.
# Arg3: client - the username of the client user.
# Pre : A socket accepts a connection with a client and a handshake occurs
#           to retrieve the client username.
# Post: The client or server terminates the connection and the chat ends.
def chat(conn, user, client):

    bufLen = MSGLEN - len(user) - 2

    while True:
        try:
            msg = conn.recv(MSGLEN)
        except error as m:
            print("ERROR: could not receive message from client... Exiting chatroom.")
            break
        if not msg or '\quit' in msg.strip().lower():
            print(client + " has left the chatroom.")
            break
        else:
            print msg

        buf = (raw_input("{}> ".format(user)))[:bufLen]
        msg = "{}> {}".format(user, buf)
        
        # even if quitting send the \quit message
        try:
            sent = sendMsg(conn, msg)
        except error as m:
            print("ERROR: could not sent message to client... Exiting chatoom.")
            break
        if buf.strip().lower() == '\quit':
            print("You have left the chatroom.")
            break


# Name: sendMsg()
# Desc: Sends the specified message to the connection up to the global max message length.
# Arg1: conn - the data connection to send data to.
# Arg2: msg - the message to send.
# Pre : A connection is previously set up and the message to send is obtained from the user.
# Post: The message is sent to the client through the connection.
def sendMsg(conn, msg):

    # python socket programming info from official docs
    # in section 
    # https://docs.python.org/2/howto/sockets.html#using-a-socket
    total = 0
    while total < MSGLEN:
        sent = conn.send(msg[total:])
        if sent == 0:
            break 
        total += sent

    return total


# Name: bye()
# Desc: Signal handler to exit the program
# Pre : CTRL + C is pressed / SIGINT signal is sent
# Post: The program is exited
def bye(signum, frame):

    # python signal handling info from official docs 
    # https://docs.python.org/2/library/signal.html
    print("") # flush
    print("chatserve is exiting... Goodbye!")
    sys.exit(0)


#########################################################################

if __name__ == "__main__":
    run()
